server:
  port: 8761
spring:
  application:
    name: eserver

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    server-url:
      defaultZone: http://localhost:8761/eureka
